social_network/urls.py
# coding=utf-8
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required as lr
import views

relationship_patterns = patterns(
    '',
    url(
        r'^friend_requests/$',
        lr(views.FriendRequestListView.as_view()),
        name='friend_requests'
    ),

    url(
        r'^friend_requests/(?P<pk>\d+)/accept/$',
        lr(views.AcceptFriendRequestView.as_view()),
        name='accept_friend_request'
    ),

    url(
        r'^friend_requests/(?P<pk>\d+)/deny/$',
        lr(views.DenyFriendRequestView.as_view()),
        name='deny_friend_request'
    ),

    url(
        r'^(?P<username>\w+)/toggle_follow/$',
        lr(views.FollowerRelationshipToggleView.as_view()),
        name="toggle_follow"
    ),

    url(
        r'^(?P<username>\w+)/follow/$',
        lr(views.FollowerRelationshipCreateView.as_view()),
        name="follow"
    ),

    url(
        r'^(?P<username>\w+)/unfollow/$',
        lr(views.FollowerRelationshipDestroyView.as_view()),
        name="unfollow"
    ),
    
    url(
        r'^(?P<username>\w+)/buttons/$',
        lr(views.FriendshipButtonsTemplateView.as_view()),
        name='friendship_buttons'
    ),

    url(
        r'^(?P<username>\w+)/request_friendship/$',
        lr(views.BaseFriendRequestCreateView.as_view()),
        name='request_friendship'
    ),

    url(
        r'^(?P<username>\w+)/request_friendship_inline/$',
        lr(views.FriendRequestCreateView.as_view()),
        name='request_friendship_inline'
    ),

    url(
        r'^(?P<username>\w+)/groups/$',
        views.UserSocialGroupList.as_view(),
        name='groups'
    ),

    url(
        r'^(?P<username>\w+)/comment/$',
        lr(views.BaseProfileCommentCreateView.as_view()),
        name="profile_comment"
    ),

    url(
        r'^(?P<username>\w+)/comment_inline/$',
        lr(views.ProfileCommentCreateView.as_view()),
        name="profile_comment_inline"
    ),

)

group_patterns = patterns(
    '',
    url(
        r'^$',
        views.SocialGroupListView.as_view(),
        name='all'
    ),

    url(
        r'^new/$',
        lr(views.BaseSocialGroupCreateView.as_view()),
        name='new'
    ),

    url(
        r'^new_inline/$',
        lr(views.SocialGroupCreateView.as_view()),
        name='new_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/$',
        views.SocialGroupDetailView.as_view(),
        name='details'
    ),

    url(
        r'^(?P<slug>[\w-]+)/members/$',
        views.SocialGroupMembersList.as_view(),
        name='members'
    ),

    url(
        r'^(?P<slug>[\w-]+)/feed/$',
        views.SocialGroupFeedView.as_view(),
        name='feed'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/$',
        lr(views.SocialGroupMembershipRequestsList.as_view()),
        name='requests'
    ),

    url(
        r'^(?P<slug>[\w-]+)/buttons/$',
        lr(views.MembershipButtonsTemplateView.as_view()),
        name='membership_buttons'
    ),

    url(
        r'^(?P<slug>[\w-]+)/edit/$',
        lr(views.BaseSocialGroupUpdateView.as_view()),
        name='edit'
    ),

    url(
        r'^(?P<slug>[\w-]+)/edit_inline/$',
        lr(views.SocialGroupUpdateView.as_view()),
        name='edit_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post/$',
        lr(views.GenericGroupPostCreateView.as_view()),
        name='post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$',
        lr(views.GenericGroupPostUpdateView.as_view()),
        name='edit_post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/delete/$',
        lr(views.GroupPostDeleteView.as_view()),
        name='delete_post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/comment/$',
        lr(views.BaseGroupCommentCreateView.as_view()),
        name='comment'
    ),

    url(
        r'^(?P<slug>[\w-]+)/comment_inline/$',
        lr(views.GroupCommentCreateView.as_view()),
        name='comment_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_link/$',
        lr(views.BaseGroupLinkCreateView.as_view()),
        name='post_link'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_link_inline/$',
        lr(views.GroupLinkCreateView.as_view()),
        name='post_link_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_photo/$',
        lr(views.BaseGroupPhotoCreateView.as_view()),
        name='post_photo'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_photo_inline/$',
        lr(views.GroupPhotoCreateView.as_view()),
        name='post_photo_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/join/$',
        lr(views.SocialGroupJoinView.as_view()),
        name='join'
    ),

    url(
        r'^(?P<slug>[\w-]+)/request_membership/$',
        lr(views.BaseSocialGroupRequestCreateView.as_view()),
        name='request_membership'
    ),

    url(
        r'^(?P<slug>[\w-]+)/request_membership_inline/$',
        lr(views.SocialGroupRequestCreateView.as_view()),
        name='request_membership_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/(?P<pk>\d+)/accept/$',
        lr(views.SocialGroupRequestAcceptView.as_view()),
        name='accept_request'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/(?P<pk>\d+)/deny/$',
        lr(views.SocialGroupRequestDenyView.as_view()),
        name='deny_request'
    ),

)

urlpatterns = patterns(
    '',
    url(
        r'^group/', include(group_patterns, namespace='group')
    ),

    url(
        r'^', include(relationship_patterns, namespace='user')
    ),
)

social_network/templates/social_network/buttons/_friendship_buttons.html
{% load social_network_tags %}
{% load i18n %}

{% if user|is_friends_with:target_user %}
    <span class="glyphicons ok_2 pull-right"><i></i>{% trans 'You and ' %}{{ target_user.get_full_name }} {% trans 'are friends' %}
    </span>
{% elif request.user|has_requested_friendship_to:target_user %}
    <span class="glyphicons ok_2 pull-right"><i></i>{% trans 'Friend request sent to ' %}{{ target_user.get_full_name }}
    </span>
{% elif target_user|has_requested_friendship_to:request.user %}
    <span class="glyphicons ok_2 pull-right"><i></i>{{ target_user.get_full_name }} {% trans 'sent you a friend request.' %}
    </span>
{% else %}
    <a href="{% url 'user:request_friendship' target_user.username %}"
       class="btn btn-primary btn-icon glyphicons ok_2 btn-sm pull-right show_modal"
       data-container="#modal_add_friend_request"><i></i>{% trans 'Send Friend Request' %}</a>
{% endif %}

social_network/templates/social_network/buttons/_membership_buttons.html
{% load social_network_tags %}
{% load i18n %}

{% is_group_member user group as is_member %}
{% if not is_member %}
    {% if group.closed %}
        {% has_requested_membership user group as membership_req %}
        {% if membership_req %}
            <span class="glyphicons ok_2 pull-right"><i></i>
                {% trans 'Membership request sent to group' %}
            </span>
        {% else %}
            <a href="{{ group.get_request_membership_url }}" data-container="#ajax_modal"
               class="btn btn-primary btn-icon glyphicons ok_2 btn-sm pull-right show_modal">
                <i></i>{% trans 'Request Membership' %}
            </a>
        {% endif %}
    {% else %}
        <a id="group_join_link" href="{{ group.get_join_url }}" class="btn btn-primary btn-sm pull-right">
            <i></i>{% trans 'Join' %}
        </a>
    {% endif %}
{% endif %}