social_network/urls.py
# coding=utf-8
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required as lr
import views

relationship_patterns = patterns(
    '',
    url(
        r'^friend_requests/$',
        lr(views.FriendRequestListView.as_view()),
        name='friend_requests'
    ),

    url(
        r'^friend_requests/(?P<pk>\d+)/accept/$',
        lr(views.AcceptFriendRequestView.as_view()),
        name='accept_friend_request'
    ),

    url(
        r'^friend_requests/(?P<pk>\d+)/deny/$',
        lr(views.DenyFriendRequestView.as_view()),
        name='deny_friend_request'
    ),

    url(
        r'^(?P<username>\w+)/toggle_follow/$',
        lr(views.FollowerRelationshipToggleView.as_view()),
        name="toggle_follow"
    ),

    url(
        r'^(?P<username>\w+)/follow/$',
        lr(views.FollowerRelationshipCreateView.as_view()),
        name="follow"
    ),

    url(
        r'^(?P<username>\w+)/unfollow/$',
        lr(views.FollowerRelationshipDestroyView.as_view()),
        name="unfollow"
    ),
    
    url(
        r'^(?P<username>\w+)/buttons/$',
        lr(views.FriendshipButtonsTemplateView.as_view()),
        name='friendship_buttons'
    ),

    url(
        r'^(?P<username>\w+)/request_friendship/$',
        lr(views.BaseFriendRequestCreateView.as_view()),
        name='request_friendship'
    ),

    url(
        r'^(?P<username>\w+)/request_friendship_inline/$',
        lr(views.FriendRequestCreateView.as_view()),
        name='request_friendship_inline'
    ),

    url(
        r'^(?P<username>\w+)/groups/$',
        views.UserSocialGroupList.as_view(),
        name='groups'
    ),

    url(
        r'^(?P<username>\w+)/comment/$',
        lr(views.BaseProfileCommentCreateView.as_view()),
        name="profile_comment"
    ),

    url(
        r'^(?P<username>\w+)/comment_inline/$',
        lr(views.ProfileCommentCreateView.as_view()),
        name="profile_comment_inline"
    ),

)

group_patterns = patterns(
    '',
    url(
        r'^$',
        views.SocialGroupListView.as_view(),
        name='all'
    ),

    url(
        r'^new/$',
        lr(views.BaseSocialGroupCreateView.as_view()),
        name='new'
    ),

    url(
        r'^new_inline/$',
        lr(views.SocialGroupCreateView.as_view()),
        name='new_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/$',
        views.SocialGroupDetailView.as_view(),
        name='details'
    ),

    url(
        r'^(?P<slug>[\w-]+)/members/$',
        views.SocialGroupMembersList.as_view(),
        name='members'
    ),

    url(
        r'^(?P<slug>[\w-]+)/feed/$',
        views.SocialGroupFeedView.as_view(),
        name='feed'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/$',
        lr(views.SocialGroupMembershipRequestsList.as_view()),
        name='requests'
    ),

    url(
        r'^(?P<slug>[\w-]+)/buttons/$',
        lr(views.MembershipButtonsTemplateView.as_view()),
        name='membership_buttons'
    ),

    url(
        r'^(?P<slug>[\w-]+)/edit/$',
        lr(views.BaseSocialGroupUpdateView.as_view()),
        name='edit'
    ),

    url(
        r'^(?P<slug>[\w-]+)/edit_inline/$',
        lr(views.SocialGroupUpdateView.as_view()),
        name='edit_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post/$',
        lr(views.GenericGroupPostCreateView.as_view()),
        name='post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$',
        lr(views.GenericGroupPostUpdateView.as_view()),
        name='edit_post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/delete/$',
        lr(views.GroupPostDeleteView.as_view()),
        name='delete_post'
    ),

    url(
        r'^(?P<slug>[\w-]+)/comment/$',
        lr(views.BaseGroupCommentCreateView.as_view()),
        name='comment'
    ),

    url(
        r'^(?P<slug>[\w-]+)/comment_inline/$',
        lr(views.GroupCommentCreateView.as_view()),
        name='comment_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_link/$',
        lr(views.BaseGroupLinkCreateView.as_view()),
        name='post_link'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_link_inline/$',
        lr(views.GroupLinkCreateView.as_view()),
        name='post_link_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_photo/$',
        lr(views.BaseGroupPhotoCreateView.as_view()),
        name='post_photo'
    ),

    url(
        r'^(?P<slug>[\w-]+)/post_photo_inline/$',
        lr(views.GroupPhotoCreateView.as_view()),
        name='post_photo_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/join/$',
        lr(views.SocialGroupJoinView.as_view()),
        name='join'
    ),

    url(
        r'^(?P<slug>[\w-]+)/request_membership/$',
        lr(views.BaseSocialGroupRequestCreateView.as_view()),
        name='request_membership'
    ),

    url(
        r'^(?P<slug>[\w-]+)/request_membership_inline/$',
        lr(views.SocialGroupRequestCreateView.as_view()),
        name='request_membership_inline'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/(?P<pk>\d+)/accept/$',
        lr(views.SocialGroupRequestAcceptView.as_view()),
        name='accept_request'
    ),

    url(
        r'^(?P<slug>[\w-]+)/requests/(?P<pk>\d+)/deny/$',
        lr(views.SocialGroupRequestDenyView.as_view()),
        name='deny_request'
    ),

)

urlpatterns = patterns(
    '',
    url(
        r'^group/', include(group_patterns, namespace='group')
    ),

    url(
        r'^', include(relationship_patterns, namespace='user')
    ),
)

social_network/forms.py
# coding=utf-8
import os
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django import forms
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.forms.util import ErrorList
from models import (
    FriendRequest,
    SocialGroup, 
    GroupPost,
    GroupMembershipRequest, 
    FeedComment,
)


class FriendRequestForm(forms.ModelForm):

    class Meta:
        model = FriendRequest
        fields = ('from_user', 'to_user', 'message')
        widgets = {
            'from_user': forms.widgets.HiddenInput,
            'to_user': forms.widgets.HiddenInput,
        }


class ProfileCommentForm(forms.ModelForm):
    class Meta:
        model = FeedComment
        fields = ('creator', 'receiver', 'comment')
        widgets = {
            'creator': forms.widgets.HiddenInput,
            'receiver': forms.widgets.HiddenInput,
        }


class SocialGroupForm(forms.ModelForm):
    administrators = forms.ModelMultipleChoiceField(User.objects.all(), required=False)

    class Meta:
        model = SocialGroup
        fields = ('creator', 'name', 'description', 'closed', 'administrators', 'site', 'image')
        widgets = {
            'creator': forms.widgets.HiddenInput,
            'site': forms.widgets.HiddenInput
        }


class GroupPostForm(forms.ModelForm):

    class Meta(object):
        model = GroupPost
        widgets = {
            'creator': forms.widgets.HiddenInput,
            'group': forms.widgets.HiddenInput
        }

    def clean(self):
        if not self.cleaned_data['group'].has_member(self.cleaned_data['creator']):
            raise ValidationError("Only members can post in groups")
        return self.cleaned_data


class GenericGroupPostForm(GroupPostForm):

    class Meta(GroupPostForm.Meta):
        fields = ('creator', 'group', 'comment', 'url')

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, instance=None):
        super(GroupPostForm, self).__init__(data, files, auto_id, prefix, initial, error_class, label_suffix,
                                            empty_permitted, instance)
        if self.instance and self.instance.url != '':
            if not self.instance.url.startswith('http://') and not self.instance.url.startswith('https://'):
                self.initial['url'] = 'http://%s%s' % (Site.objects.get_current().domain, self.instance.url)


class GroupCommentForm(GroupPostForm):

    class Meta(GroupPostForm.Meta):
        fields = ('creator', 'group', 'comment',)


class GroupSharedLinkForm(GroupPostForm):
    class Meta(GroupPostForm.Meta):
        fields = ('creator', 'group', 'url', 'comment',)


class GroupPhotoForm(GroupPostForm):

    class Meta(GroupPostForm.Meta):
        fields = ('creator', 'group', 'comment',)


class GroupMembershipRequestForm(forms.ModelForm):
    class Meta:
        model = GroupMembershipRequest
        fields = ('requester', 'group', 'message')
        widgets = {
            'requester': forms.widgets.HiddenInput,
            'group': forms.widgets.HiddenInput
        }

    def clean(self):
        if GroupMembershipRequest.objects.filter(
            requester=self.cleaned_data['requester'],
            group=self.cleaned_data['group'],
            accepted=False,
            denied=False,
        ).exists():
            raise ValidationError('Pre-existing group membership request from this user to this group.')
        return self.cleaned_data


class ShareSocialGroupForm(forms.ModelForm):
    content_type = forms.ModelChoiceField(ContentType.objects.all(), widget=forms.HiddenInput(), required=False)
    object_pk = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    groups = forms.MultipleChoiceField(
        choices=[],
        required=False,
        label=_(u'Social Groups'),
        help_text=_(u"Select Social Groups")
    )
    comment = forms.CharField(
        max_length=500, widget=forms.Textarea(attrs={'rows': 2}), required=False,
        help_text=_(u"Share something with friends and groups.")
    )

    class Meta:
        model = GroupPost
        fields = ('creator',)
        widgets = {
            'creator': forms.widgets.HiddenInput,
        }

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False):
        super(ShareSocialGroupForm, self).__init__(data, files, auto_id, prefix, initial, error_class, label_suffix,
                                                   empty_permitted)
        if initial:
            if 'groups' in initial and initial['groups'] and isinstance(initial['groups'], (list, set, tuple)):
                self.initial['groups'] = [group.pk for group in initial['groups']]

            if 'creator' not in initial or not initial['creator']:
                raise ImproperlyConfigured("The creator must be defined in the initial content.")

            self.fields['groups'].choices = [(group.pk, group.name) for group in initial['creator'].social_group_list()]

        if data:
            creator_key = self.prefix + '-creator' if self.prefix else 'creator'
            if creator_key in data and data[creator_key]:
                self.fields['groups'].choices = [(group.pk, group.name) for group in User.objects.get(pk=data[creator_key]).social_group_list()]

    def clean(self):
        cleaned_data = super(ShareSocialGroupForm, self).clean()
        if ('comment' in cleaned_data and (not cleaned_data['comment'] or cleaned_data['comment'] == "")) and cleaned_data['groups']:
            self._errors['groups'] = self.error_class(
                [_(u"You must type a comment to post in your social groups.")]
            )

        if cleaned_data['content_type'] and cleaned_data['object_pk']:
            self.content_object = cleaned_data['content_type'].get_object_for_this_type(pk=cleaned_data['object_pk'])

        return cleaned_data

    def save(self, commit=True, content_object=None):
        comment = self.cleaned_data.get('comment', None)
        groups = self.cleaned_data.get('groups', None)
        content_object = content_object or self.content_object
        if comment and comment != "" and groups and groups and content_object and commit:
            from media.models import Image
            group_post_ctype = ContentType.objects.get_for_model(GroupPost)
            group_posts = []
            for group in groups:
                url = content_object.get_absolute_url() if getattr(content_object, 'get_absolute_url', False) else content_object.get_url()
                social_group = SocialGroup.objects.get(pk=group)
                group_post = GroupPost.objects.create(
                    creator=self.cleaned_data['creator'],
                    group=social_group,
                    comment=comment,
                    url=url,
                )

                content_object_image = content_object.get_picture()
                if content_object_image.name:
                    name = content_object_image.name.split('/').pop()
                    image = Image(
                        content_type=group_post_ctype,
                        object_pk=group_post.pk,
                        caption=name,
                        creator=group_post.creator,
                        site=social_group.site,
                    )
                    image.file.save(
                        os.path.basename(name),
                        content_object_image.file,
                        False
                    )
                    image.save()

                group_posts.append(group_post)
            return group_posts
        return None

social_network/templates/social_network/group/comment.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

<form id="modal_group_comment_form" action="{{ request.path }}" method="post" >
    {% csrf_token %}
    {% render_field form.creator %}
    {% render_field form.group %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="fa fa-comment fa-lg"></i> {% trans 'Comment' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {% trans "Write your comment here..." as commentValuePH %}
                        {% render_field form.comment rows=5 class="input-block-level form-control required" placeholder=commentValuePH %}
                        {% include "social_network/errors/_error_list.html" with errors=form.comment.errors %}
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-icon btn-default glyphicons circle_remove"
                       data-dismiss="modal"><i></i>{% trans 'Cancel' %}</a>
                    <a id="btn_dialog_ok" href="#"
                       class="btn btn-icon btn-primary glyphicons circle_ok submit-modal-form"><i></i>{% trans 'Send' %}</a>
                </div>
            </div>
        </div>
</form>

social_network/templates/social_network/group/form.html
{% load i18n %}
{% load widget_tweaks %}

<!-- Modal -->
<div class="modal-dialog ">
    <div class="modal-content">

        <!-- Modal heading -->
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title"><strong>{% trans 'Create Group' %}</strong></h3>
        </div>
        <!-- // Modal heading END -->

        <!-- Modal body -->
        <form id="group_create_form" class="form-horizontal" method="post" data-submit-response="html"
              action="{{ request.path }}" enctype="multipart/form-data">
            {% csrf_token %}
            {% render_field form.creator %}
            <div class="modal-body">
                <div class="row">

                    <div class="form-group margin-left-none col-md-12">
                        <div class="input-group col-md-12 padding-none-LR">
                            <label class="padding-left-none control-label" for="id_name">{% trans 'Name' %}</label>
                            {% trans "Enter group name here..." as namePH %}
                            {% render_field form.name class+="form-control required" placeholder=namePH %}
                        </div>
                        {% include "social_network/errors/_error_list.html" with errors=form.name.errors only %}
                    </div>

                    <div class="form-group margin-left-none col-md-12">
                        {% trans "Enter group description and details..." as descriptionPH %}
                        <div class="input-group col-md-12 margin-left-none padding-none-LR">
                            <label class="control-label" for="id_description">{% trans 'Description' %}</label>
                            {% render_field form.description class+="form-control required" placeholder=descriptionPH rows=2 %}
                        </div>
                        {% include "social_network/errors/_error_list.html" with errors=form.description.errors only %}
                    </div>
                    <div class="form-group margin-left-none col-md-12  margin-right-none">
                        {% trans "Add group administrators (other than you)..." as adminsPH %}
                        <label for="id_administrators" class="control-label">{% trans "Administrators" %}:</label>
                        <div class="input-group col-md-12 margin-left-none padding-none-LR">
                            {% render_field form.administrators class+="form-control" placeholder=adminsPH %}
                        </div>
                        {% include "social_network/errors/_error_list.html" with errors=form.administrators.errors only %}
                    </div>

                    <div class="form-group col-md-12 margin-left-none">
                        <label class="top control-label" for="id_image">{% trans 'Group Picture' %}</label>

                        <div class="fileupload fileupload-new margin-none col-md-12 padding-none-LR" data-provides="fileupload">
                            <div class="input-group">
                                <div class="form-control col-md-3">
                                    <i class="fa fa-file fileupload-exists"></i>
                                    <span class="fileupload-preview"></span>
                                </div>
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        <span class="fileupload-new">{% trans 'Select' %}</span>
                                        <span class="fileupload-exists">{% trans 'Change' %}</span>
                                        {% render_field form.image class+="required"%}
                                    </span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">{% trans 'Clean' %}</a>
                                </span>
                            </div>
                        </div>
                        {% include "social_network/errors/_error_list.html" with errors=form.image.errors only %}
                    </div>

                    <div class="clearfix"></div>
                    <div class="uniformjs col-md-12">
                        <label class="checkbox  padding-top-none">
                            {% render_field form.closed %} {% trans 'I want this to be a closed group' %}
                        </label>
                    </div>
                </div>
            </div>
            <!-- // Modal body END -->
            <!-- Modal footer -->
            <div class="modal-footer ">
                <a href="#" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</a>
                <a href="#" class="btn btn-info submit-modal-form">{% trans 'Create' %}</a>
            </div>
            <!-- // Modal footer END -->
        </form>
    </div>
</div>
<!-- // Modal END -->

social_network/templates/social_network/group/link.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

<form id="modal_group_link_form" action="{{ request.path }}" method="post" >
    {% csrf_token %}
    {% render_field form.creator %}
    {% render_field form.group %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="fa fa-comment fa-lg"></i> {% trans 'Share Link' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {% trans "Write your link here..." as linkValuePH %}
                        {% render_field form.url class="input-block-level form-control required" placeholder=linkValuePH %}
                        {% include "social_network/errors/_error_list.html" with errors=form.url.errors %}
                    </div>
                    <div class="form-group">
                        {% trans "Write your comment here..." as commentValuePH %}
                        {% render_field form.comment rows=5 class="input-block-level form-control required" placeholder=commentValuePH %}
                        {% include "social_network/errors/_error_list.html" with errors=form.comment.errors %}
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-icon btn-default glyphicons circle_remove"
                       data-dismiss="modal"><i></i>{% trans 'Cancel' %}</a>
                    <a id="btn_dialog_ok" href="#"
                       class="btn btn-icon btn-primary glyphicons circle_ok submit-modal-form"><i></i>{% trans 'Send' %}</a>
                </div>
            </div>
        </div>
</form>

social_network/templates/social_network/group/list.html
{% load i18n %}
{% load static %}
{% load social_network_tags %}

<div class="separator"></div>
<!-- MY GROUPS-->
<div class="widget widget-body-white widget-heading-simple"
     {% if object_list|length > 0 %}data-toggle="collapse-widget" data-collapse-closed="false"{% endif %}>
    <div class="widget-head">
        <strong class="text-primary">
            {% trans 'Groups' %} <label class="badge badge-primary">{{ object_list|length }}</label>
        </strong>
    </div>
    {% for group in object_list %}
        <div class="">
            <div class="widget-body padding-bottom-none padding-none-LR">
                <span class="pull-right glyphicons {% if group.closed %}lock{% else %}unlock{% endif %} group-lock"><i></i></span>
                <div class="col-md-1 ">
                    <div class="widget widget-pinterest border-none">
                        <a href="{{ group.get_absolute_url }}" data-toggle="modal"
                           class="widget-body padding-none">
                            {% trans 'Group Picture' as group_picture_alt %}
                            {% if group.image %}
                                <img class="cp-carousel-catalog-image" src="{{ group.image.avatar_large.url }}" alt="{{ group_picture_alt }}"/>
                            {% else %}
                                <img class="cp-carousel-catalog-image" src="{% static 'social_network/img/group.jpeg' %}" alt="{{ group_picture_alt }}"/>
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="col-md-11">
                    <h4 class="border-bottom">
                        <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
                         [{{ group|relationship_with:username }} ]
                    </h4>
                    <p>{{ group.description }}</p>
                </div>
                <div class="clearfix"></div>
                <div class="separator-line"></div>
                {% with group.members as members_count %}
                    {% if members_count > 0 %}
                        <div class="col-md-12 innerB">
                            {% if members_count > 6 %}
                                <h5 class="col-md-12 padding-none-LR text-muted">
                                    {% blocktrans %}
                                        Members (displaying 6 of {{ members_count }})
                                    {% endblocktrans %}
                                </h5>
                            {% else %}
                                <h5 class="col-md-12 padding-none-LR text-muted">
                                    {% blocktrans %}
                                        Members (displaying {{ members_count}} of {{ members_count }})
                                    {% endblocktrans %}
                                </h5>
                            {% endif %}
                            {% for member in group.member_list %}
                                <div class="col-md-2 padding-none-LR separator top ">
                                    <a href="{{ member.profile.get_absolute_url }}">
                                        <span class="col-md-2 padding-none-LR">
                                            {% trans "Profile Picture" as profile_picture_alt %}
                                             {% if member.profile.picture %}
                                                 <img class="img-responsive"
                                                      src="{{ member.profile.picture.url }}" alt="{{ profile_picture_alt }}"/>
                                             {% else %}
                                                 <img class="img-responsive"
                                                      src="{% static 'social_network/img/group.jpeg' %}"
                                                      alt="{{ profile_picture_alt }}"/>
                                             {% endif %}
                                        </span>
                                        <span class="text-muted col-md-10 ">
                                            {{ member.get_full_name }}<br>
                                        </span>
                                    </a>
                                </div>
                            {% endfor %}
                            <div class="clearfix"></div>
                        </div>
                    {% endif %}
                {% endwith %}
                <div class="col-md-12 innerB">
                    <div class="pull-right"><a
                            href="{{ group.get_absolute_url }}">{% trans 'See more details...' %}</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="center">
            {% trans "There are no group to show..." %}
        </div>
    {% endfor %}
</div>
<!-- END MY GROUPS-->

<!--for collapsible-->
<script src="{% static "vendors/components/modules/admin/widgets/widget-collapsible/assets/widget-collapsible.init.js" %}"></script>

social_network/templates/social_network/group/photo.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

<form id="modal_group_photo_form" action="{{ request.path }}" method="post" >
    {% csrf_token %}
    {% render_field form.creator %}
    {% render_field form.group %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="fa fa-camera fa-lg"></i> {% trans 'Share a photo' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="top control-label" for="id_image">{% trans 'Picture' %}</label>
                        <div class="fileupload fileupload-new margin-none col-md-12 padding-none-LR"
                             data-provides="fileupload">
                            <div class="input-group">
                                <div class="form-control col-md-3"><i class="fa fa-file fileupload-exists"></i> <span
                                        class="fileupload-preview"></span></div>
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        <span class="fileupload-new">{% trans 'Select' %}</span>
                                        <span class="fileupload-exists">{% trans 'Change' %}</span>
                                        {% render_field form.image accept+="image/*" class+="required" %}
                                    </span><a href="#" class="btn fileupload-exists"
                                              data-dismiss="fileupload">{% trans 'Clean' %}</a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="separator"></div>
                    <div class="form-group">
                        {% trans "Write your comment..." as commentValuePH %}
                        {% render_field form.comment rows=5 class="input-block-level form-control required" placeholder=commentValuePH %}
                        {% include "social_network/errors/_error_list.html" with errors=form.comment.errors %}
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-icon btn-default glyphicons circle_remove"
                       data-dismiss="modal"><i></i>{% trans 'Cancel' %}</a>
                    <a id="btn_dialog_ok" href="#"
                       class="btn btn-icon btn-primary glyphicons circle_ok submit-modal-form"><i></i>{% trans 'Send' %}</a>
                </div>
            </div>
        </div>
</form>

social_network/templates/social_network/group/request.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

<form id="group_request_form" action="{{ request.path }}" method="post" >
    {% csrf_token %}
    {% render_field form.requester %}
    {% render_field form.group %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="fa fa-comment fa-lg"></i>{% trans 'Request Membership' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {% trans "Write your comment..." as commentValuePH %}
                        {% render_field form.message rows=5 class="input-block-level form-control required" placeholder=commentValuePH %}
                        {% include "social_network/errors/_error_list.html" with errors=form.message.errors %}
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-icon btn-default glyphicons circle_remove"
                       data-dismiss="modal"><i></i>{% trans 'Cancel' %}</a>
                    <a id="btn_dialog_ok" href="#"
                       class="btn btn-icon btn-primary glyphicons circle_ok submit-modal-form"><i></i>{% trans 'Send' %}</a>
                </div>
            </div>
        </div>
</form>